---
# Crash Course Python for Data Science - Intro to Python  
---
# 06 - Numpy
---



## STOP! BEFORE GOING ANY FURTHER...  

Remember, this exercises are open book, open neighbour, open everything! Try to do them on your own before looking at the solution samples.



### Import Numpy as Np

In [1]:
# Make sure you run this cell first
import numpy as np
print('NumPy imported!')

NumPy imported!


### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [3]:
### YOUR CODE GOES HERE ###
x = np.random.randint(0,100,(5,3))
x

array([[51,  9, 99],
       [24, 70, 21],
       [64, 18, 66],
       [16, 97,  9],
       [98, 33, 67]])

In [4]:
#@title Double click here for a sample solution

x = np.random.randint(0,100, (5,3))
x

array([[47, 93, 66],
       [18, 46, 88],
       [91, 92, 12],
       [27,  3,  7],
       [49, 56, 37]])

### Array practice

In [5]:
# Return the first row:

### YOUR CODE GOES HERE ###
x[0,]

array([47, 93, 66])

In [6]:
#@title Double click here for a sample solution

# Return the first row:
x[0,]

array([47, 93, 66])

In [9]:
# Return last column

### YOUR CODE GOES HERE ###
x[:,-1]

array([66, 88, 12,  7, 37])

In [8]:
#@title Double click here for a sample solution

# Return last column
x[:, -1]

array([66, 88, 12,  7, 37])

In [10]:
# Return the third column values from the 4th and 5th rows

### YOUR CODE GOES HERE ###
x[3:5,2]

array([ 7, 37])

In [11]:
#@title Double click here for a sample solution

# Return the third column values from the 4th and 5th rows
x[3:5,2]

array([ 7, 37])

In [12]:
# Multiply every value in the array by 2

### YOUR CODE GOES HERE ###
x*2

array([[ 94, 186, 132],
       [ 36,  92, 176],
       [182, 184,  24],
       [ 54,   6,  14],
       [ 98, 112,  74]])

In [13]:
#@title Double click here for a sample solution

# Multiply every value in the array by 2
x*2

array([[ 94, 186, 132],
       [ 36,  92, 176],
       [182, 184,  24],
       [ 54,   6,  14],
       [ 98, 112,  74]])

In [14]:
# Divide every value by 3

### YOUR CODE GOES HERE ###
x/3

array([[15.66666667, 31.        , 22.        ],
       [ 6.        , 15.33333333, 29.33333333],
       [30.33333333, 30.66666667,  4.        ],
       [ 9.        ,  1.        ,  2.33333333],
       [16.33333333, 18.66666667, 12.33333333]])

In [15]:
#@title Double click here for a sample solution

# Divide every value by 3
x/3

array([[15.66666667, 31.        , 22.        ],
       [ 6.        , 15.33333333, 29.33333333],
       [30.33333333, 30.66666667,  4.        ],
       [ 9.        ,  1.        ,  2.33333333],
       [16.33333333, 18.66666667, 12.33333333]])

In [16]:
# Increase the values in the first row by 12

### YOUR CODE GOES HERE ###
x[0,] = x[0,] + 12
x

array([[ 59, 105,  78],
       [ 18,  46,  88],
       [ 91,  92,  12],
       [ 27,   3,   7],
       [ 49,  56,  37]])

In [17]:
#@title Double click here for a sample solution

# Increase the values in the first row by 12
x[0,] = x[0,] + 12
x

array([[ 71, 117,  90],
       [ 18,  46,  88],
       [ 91,  92,  12],
       [ 27,   3,   7],
       [ 49,  56,  37]])

In [18]:
# Calculate the mean of the first column

### YOUR CODE GOES HERE ###
x[:,0].mean()

np.float64(51.2)

In [19]:
#@title Double click here for a sample solution

# Calculate the mean of the first column
x[:,0].mean()

np.float64(51.2)

In [20]:
# Calculate the median of the array after removing the 2 smallest values in the array

### YOUR CODE GOES HERE ###
x1 = np.delete(x, x.argmin())
x1 = np.delete(x1,x1.argmin())
np.median(x1)

np.float64(56.0)

In [21]:
#@title Double click here for a sample solution

# Calculate the median of the array after removing the 2 smallest values in the array
x1 = np.delete(x, x.argmin())
x1 = np.delete(x1, x1.argmin())
np.median(x1)


np.float64(56.0)

In [22]:
# Calculate the standard deviation of the first 3 rows

### YOUR CODE GOES HERE ###
np.std(x[:3],)

np.float64(34.15686399575774)

In [23]:
#@title Double click here for a sample solution

# Calculate the standard deviation of the first 3 rows
np.std(x[:3],)

np.float64(34.15686399575774)

In [24]:
# Return values in the second column greater than 25

### YOUR CODE GOES HERE ###
print('values bigger than 25 on the second column = ', x[:,1][x[:,1]>25])

values bigger than 25 on the second column =  [117  46  92  56]


In [25]:
#@title Double click here for a sample solution

# Return values in the second column greater than 25
print("Values bigger than 25 on the second column =", x[:,1][x[:,1]>25])

Values bigger than 25 on the second column = [117  46  92  56]


In [26]:
# Return values in the array under 40

### YOUR CODE GOES HERE ###
print('values under 40 in array =', x[x<40])

values under 40 in array = [18 12 27  3  7 37]


In [27]:
#@title Double click here for a sample solution

# Return values in the array under 40
print("Values under 40 in array =", x[x<40])

Values under 40 in array = [18 12 27  3  7 37]
